### ISSUE TITLE
ofxGlWarper not found

### ISSUE THREAD

**Issue by mruegenberg** [paulobarcelos/ofxWarpBlendTool#1]
When trying to build the sample, I get `fatal error: ofxGlWarper.h: No such file or directory` (on Linux).

This is because my filesystem is case-sensitive. The import in `ofxWarpBlendTool.h` needs to be `#include "ofxGLWarper.h"`.

**Comment by paulobarcelos** [comment]
Hey Marcel! I don't really have time to add this fix, would you mind doing
a pull request?

On Tuesday, 3 May 2016, Marcel Ruegenberg notifications@github.com wrote:

> When trying to build the sample, I get fatal error: ofxGlWarper.h: No
> such file or directory (on Linux).
> 
> This is because my filesystem is case-sensitive. The import in
> ofxWarpBlendTool.h needs to be #include "ofxGLWarper.h".
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/paulobarcelos/ofxWarpBlendTool/issues/1

## 

Sent from my iPhone

**Comment by mruegenberg** [comment]
Sure, I'll do one as soon as I get a working build :)
